// Test Suit for product with 20 colourways

exports.testProductItemNumber = "INTERNATIONAL_TEST_20_COLOURWAYS"
exports.testProductTitle = "Matt Emulsion 100ml Tester Pot"
exports.testColourway1ItemNumber = "1111111"
exports.testColourway1Title = "Matt Emulsion"
exports.testColourway1Colour = "Dark"
exports.testColourway1Url = "g7190s5/962950#111111"
exports.testPrice = "10 د.إ‏ - 12.50 د.إ‏"

exports.testColourwayViewMoreItemNumber = "19"

exports.apiData = {
    itemNumber: exports.testProductItemNumber,
    title: exports.testProductTitle,
    currencyCode: "AED",
    brand: "nike",
    department: "menswear",
    fit: "tall",
    colourways: [
        {
            fits: ["Regular", "Petite"],
            url: exports.testColourway1Url,
            colour: exports.testColourway1Colour,
            itemNumber: exports.testColourway1ItemNumber,
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12.5,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Bleach Wash",
            itemNumber: "920427",
            title: exports.testColourway1Title,
            overallStarRating: 2,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: 3,
                saleMaxPrice: 4,
                wasMinPrice: 5,
                wasMaxPrice: 6,
            },
        },
        {
            fits: ["Regular"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "503290",
            title: exports.testColourway1Title,
            overallStarRating: 4,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "940736",
            title: exports.testColourway1Title,
            overallStarRating: 5,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "495341",
            title: exports.testColourway1Title,
            overallStarRating: 1,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "507422",
            title: exports.testColourway1Title,
            overallStarRating: 0,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "608072",
            title: exports.testColourway1Title,
            overallStarRating: 4,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "705031",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "803745",
            title: exports.testColourway1Title,
            overallStarRating: 5,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "630710",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "326828",
            title: exports.testColourway1Title,
            overallStarRating: 2,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "768334",
            title: exports.testColourway1Title,
            overallStarRating: 1,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "966813",
            title: exports.testColourway1Title,
            overallStarRating: 0,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "745348",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "969758",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "819434",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "466748",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "313332",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: exports.testColourwayViewMoreItemNumber,
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "757786",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
        {
            fits: ["Regular/Tall", "Petite"],
            url: "g7190s5/962950#962950",
            colour: "Dark",
            itemNumber: "999204",
            title: exports.testColourway1Title,
            overallStarRating: 3,
            itemPrice: {
                minPrice: 10,
                maxPrice: 12,
                saleMinPrice: null,
                saleMaxPrice: null,
                wasMinPrice: null,
                wasMaxPrice: null,
            },
        },
    ],
}
