apiVersion: v1
kind: Service
metadata:
  name: {{include "monorepo-plp-frontend.fullname" .}}
  labels: {{- include "monorepo-plp-frontend.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.externalPort}}
      protocol: TCP
      name: http
      targetPort: {{.Values.service.internalPort}}
  selector: {{- include "monorepo-plp-frontend.selectorLabels" . | nindent 4}}
