export default Object.freeze({
    id: "000000",
    title: "------ --------- -------- -------",
    imageCdnUrl: "----",
    baseUrl: "---",
    saleSash: "-",
    saleSashPosition: "TL",
    type: "Product",
    colourways: [
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: true,
            price: "£30",
            salePrice: "-",
            associatedColourway: {
                itemPrice: {
                    minPrice: 35,
                    maxPrice: 35,
                    saleMinPrice: null,
                    saleMaxPrice: null,
                    wasMinPrice: null,
                    wasMaxPrice: null,
                },
                type: "SuitTrousers",
            },
            type: "SuitJacket",
            overallStarRating: 2,
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
        {
            fits: ["-", "-"],
            url: "-",
            colour: "-",
            id: "-",
            selected: false,
            price: "£30",
        },
    ],
})
