{{- if .Values.ingress.enabled -}}
{{- $fullName := include meganav-ui.fullname" . -}}
{{- $containerServiceName := .Values.service.containerServiceName -}}
{{- $containerServicePort := .Values.service.containerServicePort -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include meganav-ui.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
        - path: {{ .Values.ingress.pathMegaNavStatic }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
        - path: {{ .Values.ingress.pathSecondaryItems }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
        - path: {{ .Values.ingress.pathContainerPage }}
          backend:
            service:
              name: {{ $containerServiceName }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
        - path: {{ .Values.ingress.pathStaticContent }}
          backend:
            service:
              name: {{ $containerServiceName }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host | quote }}
    {{- end }}
{{- end }}
