apiVersion: v1
kind: Service
metadata:
  name: {{include meganav-ui.fullname" .}}
  labels: {{- include meganav-ui.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.externalPort}}
      protocol: TCP
      name: http
      targetPort: {{.Values.service.internalPort}}
  selector: {{- include meganav-ui.selectorLabels" . | nindent 4}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.containerServiceName}}
  labels: {{- include meganav-ui.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.externalPort}}
      protocol: TCP
      name: container-page
      targetPort: {{.Values.service.containerServicePort}}
  selector: {{- include meganav-ui.selectorLabels" . | nindent 4}}
