replicaCount: 3
Environment: Development
image:
  useImagePullSecrets: true
  pullPolicy: Always
  imagePullSecret: 'footer-imagesecret'

service:
  type: ClusterIP
  port: 80
  internalPort: 3002
  externalPort: 80
  containerServicePort: 3333
  containerServiceName: amido-ecommerce-footer-ui-container-service

ingress:
  enabled: true
  annotations: {kubernetes.io/ingress.class: 'nginx', nginx.ingress.kubernetes.io/use-regex: 'true'}
  path: '/footer(/|$)(.*)'
  pathFooterStatic: '/footerstatic(/|$)(.*)'
  pathContainerPage: '/footercontainer(/|$)(.*)'
  host:
domain: 'test.local'
enabled: true
ignore_resource_limits: false
resources: {}

nodeSelector:
  {}
  # footertest: true
# }
tolerations: []
affinity: {}
podSecurityContext: {}
securityContext: {}

application:
  appInsightsKey: 'REPLACE_ME'
  apiBaseUrl: 'REPLACE_ME'
  cdnBaseUrl: 'REPLACE_ME'
  app_entrypoint: 'REPLACE_ME'
  assets_path: 'REPLACE_ME'
  generate_sourcemap: 'REPLACE_ME'
  log_level: 'REPLACE_ME'
  blobStorageSSRBaseURL: 'REPLACE_ME'
  blob_storage_override: 'REPLACE_ME'
