trigger:
  branches:
    include:
      - feature/*
      - master
      - release/*

  paths:
    include:
      - apps/MFE/review-stars
    exclude:
      - /

resources:
  repositories:
    - repository: AmidoEcommerce
      type: git
      name: Amido.Ecommerce.Infrastructure/Amido.Ecommerce.Infrastructure.Templates

variables:
  # Global Variables
  - name: project
    value: reviewstars-frontend'
  - name: tag
    value: '$(Build.BuildId)'
  - name: namespace
    value: 'review'
  # Registrys
  - name: registryName_sx
    value: ecmbrowse02acrsxeuw
  - name: registryName_ci
    value: ecmbrowse02acrcieuw
  - name: registryName_pp
    value: ecmbrowse02acrppeuw
  - name: registryName_pd
    value: ecmbrowse02acrpdeuw
  # Subscriptions
  - name: sx_subscription
    value: 'ecmbrowse02spnsxeuw'
  - name: ci_subscription
    value: 'ecmbrowse02spncieuw'
  - name: pp_subscription
    value: 'ecmbrowse02spnppeuw'
  - name: pd_subscription
    value: 'ecmbrowse02spnpdeuw'

  # Versioning
  - name: Version.Major
    value: 0
  - name: Version.Minor
    value: 1
  - name: Version.Revision
    value: $[counter(variables['Version.Minor'], 0)]
  # Application
  - name: chart_name
    value: reviewstars-frontend'
  - name: helmOverrides
    value: 'domain=$(ingress_domain),ingress.enabled=true,domain=$(ingress_domain),application.appInsightsKey=$(appInsightsKey),application.apiBaseUrl=$(apiBaseUrl),application.cdnBaseUrl=$(cdnBaseUrl),application.appUrl=$(appUrl),application.app_serve_path_prefix=$(app_serve_path_prefix),application.assets_path=$(assets_path),application.generate_sourcemap=$(generate_sourcemap),application.log_level=$(log_level)'
  - name: helm_version
    value: 3.3.1
stages:
  - stage: Prereqs
    displayName: 'Prerequisites'
    jobs:
      - template: azDevOps/azure/templates/jobs/build-updatebuildnumber.yml
        parameters:
          build_number: '$(Version.Major).$(Version.Minor).$(Version.Revision)'

  - stage: Build
    displayName: 'Build'
    dependsOn: Prereqs
    variables:
      #  - group: Veracode
      - group: 'SX.Amido.Ecommerce.ReviewStars.Frontend.EUN'
    jobs:
      - template: azDevOps/azure/templates/jobs/build-docker.yml
        parameters:
          projectName: $(project)
          registryName: $(registryName_sx)
          dockerContext: 'apps/MFE/review-stars/'
          docker_build_args: '--build-arg ASSETS_PATH=$(assets_path)'
          dockerfile_name: 'Dockerfile'
          nugetRestore: false
          dockerBuildTarget: 'test'
          testfileString: 'junit.xml'
          search: true
          searchfolders: |
            /app
          sourceFolder: '/testresults'
          imagefilter: 'label=test=true'
          testresultsfiles: '**/junit.xml'
          testResultsFormat: 'JUnit'
          host_port: 3007
          disabledruleoptions: 'document-title,html-has-lang'
          subscription: '$(sx_subscription)'
          service_connection: 'prisma_compute'
          scan_image: 'true'
        #  accessibilityTesting: false #Remove this line once tests are written.
        #  veracodeScan: true
        #  appId: '1113986'
        #  applicationType: 'frontend'
        #  appName: 'Amido.Ecommerce.ReviewStars.Frontend'
        #  wrapperZip: $(wrapper_zip)
        #  vId: $(vid)
        #  vKey: $(vkey)
        #  autoScan: true

      - job: Helm_Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: azDevOps/azure/templates/steps/pack-helm.yml # Template reference
            parameters:
              projectName: $(project)
              registryName: $(registryName_sx)
              Subscription: '$(sx_subscription)'
              context: $(system.defaultWorkingDirectory)/apps/MFE/review-stars/charts/reviewstars-frontend/

  - stage: deploy_sandbox_eun
    displayName: 'Deploy Sandbox EUN'
    dependsOn: Build
    condition: and(succeeded('Build'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))))
    variables:
      - group: 'SX.Amido.Ecommerce.ReviewStars.Frontend.EUN'
    jobs:
      - template: azDevOps/azure/templates/jobs/deploy-helm.yml
        parameters:
          environmentName: 'sx'
          # Platform Authentication
          kubernetes_service_connection: 'Kubernetes_Sandbox.eCommerce_Browse02_EUN'
          acr_service_connection: '$(sx_subscription)'
          # Registry Configuration
          registry_name: $(registryName_sx)
          registry_login: '$(registryLogin)'
          registry_pass: '$(registryPassword)'
          # Resource Configuration
          helm_version: $(helm_version)
          chart_name: $(chart_name)
          overrides: $(helmOverrides)
          namespace: $(namespace)

  - stage: deploy_sandbox_euw
    displayName: 'Deploy Sandbox EUW'
    dependsOn: Build
    condition: and(succeeded('Build'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))))
    variables:
      - group: 'SX.Amido.Ecommerce.ReviewStars.Frontend.EUW'
    jobs:
      - template: azDevOps/azure/templates/jobs/deploy-helm.yml
        parameters:
          environmentName: 'sx'
          # Platform Authentication
          kubernetes_service_connection: 'Kubernetes_Sandbox.eCommerce_Browse02_EUW'
          acr_service_connection: '$(sx_subscription)'
          # Registry Configuration
          registry_name: $(registryName_sx)
          registry_login: '$(registryLogin)'
          registry_pass: '$(registryPassword)'
          # Resource Configuration
          helm_version: $(helm_version)
          chart_name: $(chart_name)
          overrides: $(helmOverrides)
          namespace: $(namespace)

  - stage: promote_ci
    displayName: 'Promote to CI'
    dependsOn:
      - Build
      - deploy_sandbox_eun
      - deploy_sandbox_euw
    condition:
      and(succeeded('Build'), or(and(succeeded('deploy_sandbox_eun'), succeeded('deploy_sandbox_euw'),
      eq(variables['Build.SourceBranch'], 'refs/heads/master')), startsWith(variables['Build.SourceBranch'],
      'refs/heads/release/')))
    jobs:
      - template: azDevOps/azure/templates/jobs/promote-container.yml
        parameters:
          source_container_name: $(project)
          destination_container_name: $(project)
          source_acr: $(registryName_sx)
          destination_acr: $(registryName_ci)
          source_subscription: '$(sx_subscription)'
          destination_subscription: '$(ci_subscription)'
          tag: $(Build.BuildNumber)

  - stage: deploy_ci_eun
    displayName: 'Deploy CI EUN'
    dependsOn: promote_ci
    condition: succeeded('promote_ci')
    variables:
      - group: 'CI.Amido.Ecommerce.ReviewStars.Frontend.EUN'
    jobs:
      - template: azDevOps/azure/templates/jobs/deploy-helm.yml
        parameters:
          environmentName: 'ci'
          kubernetes_service_connection: 'Kubernetes_CI.eCommerce_Browse02_EUN'
          registry_name: $(registryName_ci)
          registry_login: '$(registryLogin)'
          registry_pass: '$(registryPassword)'
          helm_version: $(helm_version)
          chart_name: $(chart_name)
          overrides: $(helmOverrides)
          namespace: $(namespace)
          acr_service_connection: '$(ci_subscription)'

  - stage: deploy_ci_euw
    displayName: 'Deploy CI EUW'
    dependsOn: promote_ci
    condition: succeeded('promote_ci')
    variables:
      - group: 'CI.Amido.Ecommerce.ReviewStars.Frontend.EUW'
    jobs:
      - template: azDevOps/azure/templates/jobs/deploy-helm.yml
        parameters:
          environmentName: 'ci'
          kubernetes_service_connection: 'Kubernetes_CI.eCommerce_Browse02_EUW'
          registry_name: $(registryName_ci)
          registry_login: '$(registryLogin)'
          registry_pass: '$(registryPassword)'
          helm_version: $(helm_version)
          chart_name: $(chart_name)
          overrides: $(helmOverrides)
          namespace: $(namespace)
          acr_service_connection: '$(ci_subscription)'

    # Promote To PP ACR
  - stage: promote_preprod
    displayName: 'Promote to Pre-Prod'
    dependsOn:
      - Build
      - deploy_ci_eun
      - deploy_ci_euw
    condition:
      and(succeeded('Build'), succeeded('deploy_ci_eun'), succeeded('deploy_ci_euw'),
      startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
    jobs:
      - template: azDevOps/azure/templates/jobs/promote-container.yml
        parameters:
          source_container_name: $(project)
          destination_container_name: $(project)
          source_acr: $(registryName_ci)
          destination_acr: $(registryName_pp)
          source_subscription: '$(ci_subscription)'
          destination_subscription: '$(pp_subscription)'
          tag: $(Build.BuildNumber)

  - stage: deploy_preprod_eun
    displayName: 'Deploy PreProd EUN'
    dependsOn: promote_preprod
    condition: succeeded('promote_preprod')
    variables:
      - group: 'PP.Amido.Ecommerce.ReviewStars.Frontend.EUN'
    jobs:
      - template: azDevOps/azure/templates/jobs/deploy-helm.yml
        parameters:
          environmentName: 'pp'
          kubernetes_service_connection: 'Kubernetes_PreProd.eCommerce_Browse02_EUN'
          registry_name: $(registryName_pp)
          registry_login: '$(registryLogin)'
          registry_pass: '$(registryPassword)'
          helm_version: $(helm_version)
          chart_name: $(chart_name)
          overrides: $(helmOverrides)
          namespace: $(namespace)
          acr_service_connection: '$(pp_subscription)'

  - stage: deploy_preprod_euw
    displayName: 'Deploy PreProd EUW'
    dependsOn: promote_preprod
    condition: succeeded('promote_preprod')
    variables:
      - group: 'PP.Amido.Ecommerce.ReviewStars.Frontend.EUW'
    jobs:
      - template: azDevOps/azure/templates/jobs/deploy-helm.yml
        parameters:
          environmentName: 'pp'
          kubernetes_service_connection: 'Kubernetes_PreProd.eCommerce_Browse02_EUW'
          registry_name: $(registryName_pp)
          registry_login: '$(registryLogin)'
          registry_pass: '$(registryPassword)'
          helm_version: $(helm_version)
          chart_name: $(chart_name)
          overrides: $(helmOverrides)
          namespace: $(namespace)
          acr_service_connection: '$(pp_subscription)'

  - stage: 'Create_ServiceNow_Change'
    displayName: 'Raise ServiceNow Change'
    dependsOn:
      - Build
      - deploy_preprod_eun
      - deploy_preprod_euw
    condition:
      and(succeeded('Build'), succeeded('deploy_preprod_eun'), succeeded('deploy_preprod_euw'),
      startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
    variables:
      - group: 'ServiceNow'
      - name: 'Environment'
        value: 'Production'
    jobs:
      - deployment: ServiceNowChangeRaise
        environment: 'pd'
      - job: servicenow_raise_change
        displayName: 'Raise Change'
        steps:
          - task: ServiceNow-Change-Rasiser@0
            inputs:
              apiEndpoint: $(snowApi)
              deploymentsDictionaryAPI: $(deploymentsApi)
              buildNumber: '$(Build.BuildId)' #Must match in both stages
              currentRepository: '$(Build.Repository.Name)' #Must match in both stages
              deploymentEnvironment: '$(Environment)' #Must match in both stages
              apiUser: $(snowUsername)
              apiPassword: $(snowPassword)
              snShortDescription: 'Deployment of $(Build.Repository.Name) to $(Environment) AKS Clusters'
              snDescription: 'Deploy Release $(Build.BuildId) of the Cloud Based Review Service onto the Production AKS
                clusters (ecombrowse00akspdeun/ecmbrowse00akspdeuw). $(Build.SourceVersionMessage)' #Commit message gets inserted as the description
              snJustification:
                'This change is required to allow the automated update of $(Build.Repository.Name) onto $(Environment)'
              snCategory: 'Applications Software'
              snTestPlan:
                'This change has been tested on the UAT and Conv environments. Once this has been deployed onto
                $(Environment), our QA team will carry out any testing that is required and provide signoff.'
              snRiskImpactAnalaysis: 'Any issues could mean that the Review does not function correctly.'
              snImplementationPlan:
                'The pipeline will continue to run once this change is approved -
                $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/?buildId=$(Build.BuildId). This will
                deploy $(Build.Repository.Name) onto $(Environment). The pipeline is being run from the following branch
                - $(Build.SourceBranch).'
              snBackoutPlan:
                'The current working release will be redeployed onto $(Environment) and the QA team will re-test to
                ensure that we are back to a working state.'
              snAssignmentGroup: 'eCommerce'
              snCmdbCi: amido.com'

  - stage: 'Check_ServiceNow_Change'
    displayName: 'Check ServiceNow Change'
    dependsOn:
      - Create_ServiceNow_Change
    condition: succeeded('Create_ServiceNow_Change')
    variables:
      - group: 'ServiceNow'
      - name: 'Environment'
        value: 'Production'
    jobs:
      - deployment: 'ServiceNowChangeCheck'
        environment: 'pd'
      - job: servicenow_change_status_check
        displayName: 'Check Change Status on ServiceNow'
        steps:
          - task: ServiceNow-Change-Status-Checker@0
            inputs:
              apiEndpoint: $(snowApi)
              deploymentsDictionaryAPI: $(deploymentsApi)
              buildNumber: '$(Build.BuildId)' #Must match in both stages
              currentRepository: '$(Build.Repository.Name)' #Must match in both stages
              deploymentEnvironment: '$(Environment)' #Must match in both stages
              apiUser: '$(snowUsername)'
              apiPassword: '$(snowPassword)'
