apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include reviewstars-frontend.fullname" .}}
  labels: {{- include reviewstars-frontend.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: {{- include reviewstars-frontend.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include reviewstars-frontend.selectorLabels" . | nindent 8}}
    spec:
      imagePullSecrets:
        - name: {{.Values.image.imagePullSecret}}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8}}
      containers:
        - name: {{.Chart.Name}}
          securityContext: {{- toYaml .Values.securityContext | nindent 12}}
          image: '{{ .Values.image.repository }}:{{ .Chart.AppVersion }}'
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 80
          #   httpGet:
          #     path: /
          #     port: http
          resources: {{- toYaml .Values.resources | nindent 12}}
          env:
            - name: REACT_APP_API_BASEURL
              value: {{.Values.application.apiBaseUrl}}
            - name: REACT_APP_CDN_BASEURL
              value: {{.Values.application.cdnBaseUrl}}
            - name: REACT_APP_APPINSIGHTS_KEY
              value: {{.Values.application.appInsightsKey}}
            - name: REACT_APP_SERVE_PATH_PREFIX
              value: {{.Values.application.app_serve_path_prefix}}
            - name: ASSETS_PATH
              value: {{.Values.application.assets_path}}
            - name: PORT
              value: '3007'
            - name: GENERATE_SOURCEMAP
              value: {{.Values.application.generate_sourcemap}}
            - name: LOG_LEVEL
              value: {{.Values.application.log_level}}
