export const mockCountriesData = [
    {
        Name: "nl",
        Country: "Netherlands",
        CountryCode: "NL",
        DisplayText: "Netherlands (€)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "nl",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/nl/en",
                AccountDomainUrl: "account.amido.com/nl/en",
            },
            {
                Name: "nl",
                Value: "Nederlands ",
                TargetUrl: "http://www.amido.com/nl/nl",
                AccountDomainUrl: "account.amido.com/nl/nl",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/nl.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "ae",
        Country: "United Arab Emirates",
        CountryCode: "AE",
        DisplayText: "United Arab Emirates (AED)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.ae/en",
                AccountDomainUrl: "account.amido.ae/en",
            },
            {
                Name: "ar",
                Value: "العربية ",
                TargetUrl: "http://www.amido.ae/ar",
                AccountDomainUrl: "account.amido.ae/ar",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/ae.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Middle East / Africa",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "gb",
        Country: "United Kingdom",
        CountryCode: "GB",
        DisplayText: "United Kingdom (£)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "//www.amido.com",
                AccountDomainUrl: "www.amido.com/",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/gb.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 1,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "",
        Country: "British Forces Post Office",
        CountryCode: "",
        DisplayText: "British Forces Post Office ",
        NativeCountryText: "",
        RedirectUrl: "http://www.amido.com/bfpo",
        DefaultLanguageName: "",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/bfpo",
                AccountDomainUrl: "",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/bfpo.png",
        DisplaySequenceAttribute: "AAAAAAZ",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "test",
        Country: "Test Country",
        CountryCode: "TTT",
        DisplayText: "TEST COUNTRY",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "TTT",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/nl/en",
                AccountDomainUrl: "account.amido.com/nl/en",
            },
            {
                Name: "nl",
                Value: "Nederlands ",
                TargetUrl: "http://www.amido.com/nl/nl",
                AccountDomainUrl: "account.amido.com/nl/nl",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/nl.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: true,
        HideInPage: false,
        IsROW: false,
    },
]

export const mockCountriesDataWithoutBFPO = [
    {
        Name: "nl",
        Country: "Netherlands",
        CountryCode: "NL",
        DisplayText: "Netherlands (€)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "nl",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/nl/en",
                AccountDomainUrl: "account.amido.com/nl/en",
            },
            {
                Name: "nl",
                Value: "Nederlands ",
                TargetUrl: "http://www.amido.com/nl/nl",
                AccountDomainUrl: "account.amido.com/nl/nl",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/nl.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "ae",
        Country: "United Arab Emirates",
        CountryCode: "AE",
        DisplayText: "United Arab Emirates (AED)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.ae/en",
                AccountDomainUrl: "account.amido.ae/en",
            },
            {
                Name: "ar",
                Value: "العربية ",
                TargetUrl: "http://www.amido.ae/ar",
                AccountDomainUrl: "account.amido.ae/ar",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/ae.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Middle East / Africa",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "gb",
        Country: "United Kingdom",
        CountryCode: "GB",
        DisplayText: "United Kingdom (£)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "//www.amido.com",
                AccountDomainUrl: "www.amido.com/",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/gb.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 1,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "test",
        Country: "Test Country",
        CountryCode: "TTT",
        DisplayText: "TEST COUNTRY",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "TTT",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/nl/en",
                AccountDomainUrl: "account.amido.com/nl/en",
            },
            {
                Name: "nl",
                Value: "Nederlands ",
                TargetUrl: "http://www.amido.com/nl/nl",
                AccountDomainUrl: "account.amido.com/nl/nl",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/nl.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: true,
        HideInPage: false,
        IsROW: false,
    },
]

export const mockCountriesDataWithBFPOCorrected = [
    {
        Name: "nl",
        Country: "Netherlands",
        CountryCode: "NL",
        DisplayText: "Netherlands (€)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "nl",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/nl/en",
                AccountDomainUrl: "account.amido.com/nl/en",
            },
            {
                Name: "nl",
                Value: "Nederlands ",
                TargetUrl: "http://www.amido.com/nl/nl",
                AccountDomainUrl: "account.amido.com/nl/nl",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/nl.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "ae",
        Country: "United Arab Emirates",
        CountryCode: "AE",
        DisplayText: "United Arab Emirates (AED)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.ae/en",
                AccountDomainUrl: "account.amido.ae/en",
            },
            {
                Name: "ar",
                Value: "العربية ",
                TargetUrl: "http://www.amido.ae/ar",
                AccountDomainUrl: "account.amido.ae/ar",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/ae.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 0,
        Region: "Middle East / Africa",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "gb",
        Country: "United Kingdom",
        CountryCode: "GB",
        DisplayText: "United Kingdom (£)",
        NativeCountryText: "",
        RedirectUrl: "",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "//www.amido.com",
                AccountDomainUrl: "www.amido.com/",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/gb.png",
        DisplaySequenceAttribute: "",
        PromotedFlagIndex: 1,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
    {
        Name: "bfpo",
        Country: "British Forces Post Office",
        CountryCode: "BFPO",
        DisplayText: "British Forces Post Office ",
        NativeCountryText: "",
        RedirectUrl: "http://www.amido.com/bfpo",
        DefaultLanguageName: "en",
        Languages: [
            {
                Name: "en",
                Value: "English",
                TargetUrl: "http://www.amido.com/bfpo",
                AccountDomainUrl: "",
            },
        ],
        iconUrl: "/static-content/icons/shared/countryflags/bfpo.png",
        DisplaySequenceAttribute: "AAAAAAZ",
        PromotedFlagIndex: 0,
        Region: "Europe",
        DomainType: "",
        HideInDropdown: false,
        HideInPage: false,
        IsROW: false,
    },
]
