export const sofaItem = {
    ItemID: 4,
    ItemNumber: "512342",
    OptionNo: "25",
    SizeDescription: "Corner Chaise - Right Hand (4 seats)",
    Price: "1050.00",
    Quantity: 1,
    StockStatus: "delayed",
    StockMessage: "Delivered within 12-13 Weeks",
    WarrantyItem: null,
    Description: "MICHIGANF TWBLE MGRY",
    Url: "/homeware/sofas-chairs/michigan",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: true,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "sofas",
    AlternativeDescription: "Michigan|in Tweedy Blend Mid Grey and Slim Block - Light Feet",
    LinkedItems: null,
    GroupID: null,
    Chain: null,
    PriceFormatted: "£1,050.00",
    TotalPriceFormatted: "£1,050.00",
    CanSaveForLater: true,
    IsDiscount: false,
    Colour: null,
    Personalisation: "",
    DDFulfiller: "",
    PersonalisationReference: "",
    PersonalisationFields: [],
    Fit: null,
    Department: "NOT_IN_USE",
    PersonalisedGiftTheme: "",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "MICHIGANF TWBLE MGRY",
    EnglishSizeDescription: "Corner Chaise - Right Hand (4 seats)",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: null,
    CustomItemReference: null,
    CustomItemFields: [],
    FulfilmentType: null,
    CustomItemType: null,
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: true,
    ItemBrand: null,
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
}

export const sofaItemWithLinkedItem = {
    ItemID: 4,
    ItemNumber: "512342",
    OptionNo: "25",
    SizeDescription: "Corner Chaise - Right Hand (4 seats)",
    Price: "1050.00",
    Quantity: 1,
    StockStatus: "delayed",
    StockMessage: "Delivered within 12-13 Weeks",
    WarrantyItem: null,
    Description: "MICHIGANF TWBLE MGRY",
    Url: "/homeware/sofas-chairs/michigan",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: true,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "sofas",
    AlternativeDescription: "Michigan|in Tweedy Blend Mid Grey and Slim Block - Light Feet",
    GroupID: null,
    Chain: null,
    PriceFormatted: "£1,050.00",
    TotalPriceFormatted: "£1,050.00",
    CanSaveForLater: true,
    IsDiscount: false,
    Colour: null,
    Personalisation: "",
    DDFulfiller: "",
    PersonalisationReference: "",
    PersonalisationFields: [],
    Fit: null,
    Department: "NOT_IN_USE",
    PersonalisedGiftTheme: "",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "MICHIGANF TWBLE MGRY",
    EnglishSizeDescription: "Corner Chaise - Right Hand (4 seats)",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: null,
    CustomItemReference: null,
    CustomItemFields: [],
    FulfilmentType: null,
    CustomItemType: null,
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: true,
    ItemBrand: null,
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
    LinkedItems: [
        {
            ItemID: 0,
            ItemNumber: "179736",
            OptionNo: "01",
            SizeDescription: "",
            Price: "0",
            Quantity: 1,
            StockStatus: "delayed",
            StockMessage: "",
            WarrantyItem: null,
            Description: "",
            Url: "",
            PublicationCode: "",
            IsSalePrice: false,
            IsMultibuyItem: false,
            SpecformMessage: "",
            CanOrder: false,
            CanUpdateSize: true,
            CanUpdateQty: true,
            MaxQuantity: 0,
            MultibuyDiscountAppliedItems: null,
            ItemCategory: null,
            AlternativeDescription: null,
            LinkedItems: null,
            GroupID: null,
            Chain: null,
            PriceFormatted: null,
            TotalPriceFormatted: null,
            CanSaveForLater: true,
            IsDiscount: false,
            Colour: null,
            Personalisation: "",
            DDFulfiller: "",
            PersonalisationReference: "",
            PersonalisationFields: [],
            Fit: null,
            Department: "NOT_IN_USE",
            PersonalisedGiftTheme: "",
            CistStoreId: null,
            IsCistItem: false,
            CistDate: null,
            CistStoreName: null,
            CistStoreDisplayAddress: null,
            CistStorePoscode: null,
            CistBranchNumberPrefix: null,
            EnglishDescription: null,
            EnglishSizeDescription: null,
            SaleClearanceSofaImage: null,
            CistAmidoOpeningTimes: null,
            SearchDescription: null,
            CustomItemReference: null,
            CustomItemFields: [],
            FulfilmentType: null,
            CustomItemType: null,
            PremiumSiteIndicator: null,
            IsHighRiskItem: false,
            ItemBrand: null,
        },
    ],
}

export const personalisedItemWithoutImage = {
    ItemID: 2,
    ItemNumber: "466723",
    OptionNo: "30",
    SizeDescription: "1.5-2 Yrs",
    Price: "16.00",
    Quantity: 1,
    StockStatus: "instock",
    StockMessage: "Delivered within 14-15 Days",
    WarrantyItem: null,
    Description: "Personalised Bear Cub Family Pyjamas",
    Url: "/",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: true,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "Pyjamas",
    AlternativeDescription: "",
    LinkedItems: [],
    GroupID: null,
    Chain: "Q",
    PriceFormatted: "£16.00",
    TotalPriceFormatted: "£16.00",
    CanSaveForLater: false,
    IsDiscount: false,
    Colour: "Red",
    Personalisation: "Y",
    DDFulfiller: "CG",
    PersonalisationReference: "747A3436F15FB52B59",
    PersonalisationFields: [
        {
            Field: "Above Bear, bottom line of text, centralised",
            Value: "Test 2",
        },
    ],
    Fit: "Regular",
    Department: "Homeware",
    PersonalisedGiftTheme: "1",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "Personalised Bear Cub Family Pyjamas",
    EnglishSizeDescription: "1.5-2 Yrs",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: "Personalised Bear Cub Family Pyjamas",
    CustomItemReference: null,
    CustomItemFields: [],
    FulfilmentType: "P",
    CustomItemType: null,
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: false,
    ItemBrand: "Amido",
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
}

export const personalisedItemWithImage = {
    ...personalisedItemWithoutImage,
    PersonalisationFields: [
        {
            Field: "image",
            Value: "https://g3d-app.com/u/product-state/A6/52/9F/65/E9/5F/B5/2B/59/thumbnails/thumbnail.png",
        },
    ],
}

export const customisedItemWithoutImage = {
    ItemID: 1,
    ItemNumber: "378766",
    OptionNo: "01",
    SizeDescription: "ONE",
    Price: "217.44",
    Quantity: 1,
    StockStatus: "instock",
    StockMessage: "Delivered within 25-26 Days",
    WarrantyItem: null,
    Description: "Cotton Silver Made To Measure Curtains",
    Url: "/style/st451991/378766",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: false,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "Curtains",
    AlternativeDescription: "",
    LinkedItems: [],
    GroupID: null,
    Chain: "Q",
    PriceFormatted: "£217.44",
    TotalPriceFormatted: "£217.44",
    CanSaveForLater: false,
    IsDiscount: false,
    Colour: "Silver",
    Personalisation: "Y",
    DDFulfiller: "CG",
    PersonalisationReference: "",
    PersonalisationFields: [],
    Fit: "Regular",
    Department: "Homeware",
    PersonalisedGiftTheme: "0",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "Cotton Silver Made To Measure Curtains",
    EnglishSizeDescription: "ONE",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: "Cotton Silver Made To Measure Curtains",
    CustomItemReference: "94E2A417C35FB64496",
    CustomItemFields: [
        {
            Field: "Width",
            Value: "3000mm",
        },
        {
            Field: "Height",
            Value: "400mm",
        },
        {
            Field: "Single/Pair",
            Value: "Pair",
        },
        {
            Field: "Heading",
            Value: '6" Pencil Pleat',
        },
        {
            Field: "Lining",
            Value: "House Twill",
        },
        {
            Field: "Interlining",
            Value: "No",
        },
        {
            Field: "Lining Colour",
            Value: "Ivory",
        },
    ],
    FulfilmentType: "M",
    CustomItemType: "Curtain",
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: false,
    ItemBrand: "Amido",
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
}

export const customisedItemWithNoSofaAndNoPersonalisation = {
    ItemID: 1,
    ItemNumber: "378766",
    OptionNo: "01",
    SizeDescription: "ONE",
    Price: "217.44",
    Quantity: 1,
    StockStatus: "instock",
    StockMessage: "Delivered within 25-26 Days",
    WarrantyItem: null,
    Description: "Cotton Silver Made To Measure Curtains",
    Url: "/style/st451991/378766",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: false,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "Curtains",
    AlternativeDescription: "",
    LinkedItems: [],
    GroupID: null,
    Chain: "Q",
    PriceFormatted: "£217.44",
    TotalPriceFormatted: "£217.44",
    CanSaveForLater: false,
    IsDiscount: false,
    Colour: "Silver",
    Personalisation: "N",
    DDFulfiller: "CG",
    PersonalisationReference: "",
    PersonalisationFields: [
        {
            Field: "image",
            Value: "https://d1k4nx4h9hlizo.cloudfront.net/m2m/images/NX-10066_PP6.jpg",
        },
        {
            Field: "Width",
            Value: "3000mm",
        },
    ],
    Fit: "Regular",
    Department: "Homeware",
    PersonalisedGiftTheme: "0",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "Cotton Silver Made To Measure Curtains",
    EnglishSizeDescription: "ONE",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: "Cotton Silver Made To Measure Curtains",
    CustomItemReference: "94E2A417C35FB64496",
    CustomItemFields: [],
    FulfilmentType: "M",
    CustomItemType: "Curtain",
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: false,
    ItemBrand: "Amido",
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
}

export const customisedItemWithImage = {
    ItemID: 1,
    ItemNumber: "378766",
    OptionNo: "01",
    SizeDescription: "ONE",
    Price: "217.44",
    Quantity: 1,
    StockStatus: "instock",
    StockMessage: "Delivered within 25-26 Days",
    WarrantyItem: null,
    Description: "Cotton Silver Made To Measure Curtains",
    Url: "/style/st451991/378766",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: false,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "Curtains",
    AlternativeDescription: "",
    LinkedItems: [],
    GroupID: null,
    Chain: "Q",
    PriceFormatted: "£217.44",
    TotalPriceFormatted: "£217.44",
    CanSaveForLater: false,
    IsDiscount: false,
    Colour: "Silver",
    Personalisation: "Y",
    DDFulfiller: "CG",
    PersonalisationReference: "",
    PersonalisationFields: [],
    Fit: "Regular",
    Department: "Homeware",
    PersonalisedGiftTheme: "0",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "Cotton Silver Made To Measure Curtains",
    EnglishSizeDescription: "ONE",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: "Cotton Silver Made To Measure Curtains",
    CustomItemReference: "94E2A417C35FB64496",
    CustomItemFields: [
        {
            Field: "image",
            Value: "https://d1k4nx4h9hlizo.cloudfront.net/m2m/images/NX-10066_PP6.jpg",
        },
        {
            Field: "Width",
            Value: "3000mm",
        },
        {
            Field: "Height",
            Value: "400mm",
        },
        {
            Field: "Single/Pair",
            Value: "Pair",
        },
        {
            Field: "Heading",
            Value: '6" Pencil Pleat',
        },
        {
            Field: "Lining",
            Value: "House Twill",
        },
        {
            Field: "Interlining",
            Value: "No",
        },
        {
            Field: "Lining Colour",
            Value: "Ivory",
        },
    ],
    FulfilmentType: "M",
    CustomItemType: "Curtain",
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: false,
    ItemBrand: "Amido",
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
}

export const chairItem = {
    ItemID: 7,
    ItemNumber: "351474",
    OptionNo: "01",
    SizeDescription: "ONE",
    Price: "199.00",
    Quantity: 1,
    StockStatus: "instock",
    StockMessage: "In Stock",
    WarrantyItem: null,
    Description: "Dottie Wool Blend Grey Rocker Chair",
    Url: "/g2464s1/351474",
    PublicationCode: "",
    IsSalePrice: false,
    IsMultibuyItem: false,
    SpecformMessage: "",
    CanOrder: true,
    CanUpdateSize: false,
    CanUpdateQty: true,
    MaxQuantity: 9,
    MultibuyDiscountAppliedItems: null,
    ItemCategory: "Chairs",
    AlternativeDescription: "",
    LinkedItems: [],
    GroupID: null,
    Chain: "I",
    PriceFormatted: "£199.00",
    TotalPriceFormatted: "£199.00",
    CanSaveForLater: true,
    IsDiscount: false,
    Colour: null,
    Personalisation: "N",
    DDFulfiller: "",
    PersonalisationReference: "",
    PersonalisationFields: [],
    Fit: "",
    Department: "NOT_IN_USE",
    PersonalisedGiftTheme: "0",
    CistStoreId: null,
    IsCistItem: false,
    CistDate: null,
    CistStoreName: null,
    CistStoreDisplayAddress: null,
    CistStorePoscode: null,
    CistBranchNumberPrefix: null,
    EnglishDescription: "Dottie Wool Blend Grey Rocker Chair",
    EnglishSizeDescription: "ONE",
    SaleClearanceSofaImage: null,
    CistAmidoOpeningTimes: null,
    SearchDescription: "Dottie Wool Blend Grey Rocker Chair",
    CustomItemReference: null,
    CustomItemFields: [],
    FulfilmentType: "",
    CustomItemType: null,
    PremiumSiteIndicator: "NE",
    IsHighRiskItem: false,
    ItemBrand: "",
    ProductName: "Corner Chaise - Right Hand (4 seats)",
    TPSearchDescription: "Corner Chaise - Right Hand (4 seats)",
}
