replicaCount: 3
Environment: Development
image:
  useImagePullSecrets: true
  pullPolicy: Always
  imagePullSecret: 'seometadata-imagesecret'

service:
  type: ClusterIP
  port: 80
  internalPort: 3000
  externalPort: 80

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: 'nginx',
    nginx.ingress.kubernetes.io/use-regex: 'true'
  }
  path: '/seo(/|$)(.*)'
domain: 'test.local'
enabled: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext: {}
securityContext: {}

application:
  appInsightsKey: 'REPLACE_ME'
  apiBaseUrl: 'REPLACE_ME'
  appUrl: 'REPLACE_ME'
  generate_sourcemap: 'REPLACE_ME'
  log_level: 'REPLACE_ME'
